'use client';
import React, { useState, useEffect } from 'react';
import { FileText, Check, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { getPlatformSettings, savePlatformSettings } from '@/lib/finance';

export default function AdminReportsPage() {
  const [saved, setSaved] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [settings, setSettings] = useState({
    pdf_report_title: 'Smart Pocket Financial Report',
    pdf_footer_text: 'Generated by Smart Pocket — Personal Finance, Simplified',
    pdf_include_logo: true,
    pdf_show_page_numbers: true,
    pdf_date_format: 'DD/MM/YYYY',
    pdf_currency: '',
    pdf_paper_size: 'A4',
    pdf_orientation: 'portrait',
  });

  useEffect(() => {
    getPlatformSettings()
      .then((data) => {
        if (data) {
          setSettings((s) => ({
            pdf_report_title: data.pdf_report_title || s.pdf_report_title,
            pdf_footer_text: data.pdf_footer_text || s.pdf_footer_text,
            pdf_include_logo: data.pdf_include_logo ?? s.pdf_include_logo,
            pdf_show_page_numbers: data.pdf_show_page_numbers ?? s.pdf_show_page_numbers,
            pdf_date_format: data.pdf_date_format || s.pdf_date_format,
            pdf_currency: data.pdf_currency || data.default_currency || s.pdf_currency,
            pdf_paper_size: data.pdf_paper_size || s.pdf_paper_size,
            pdf_orientation: data.pdf_orientation || s.pdf_orientation,
          }));
        }
      })
      .catch(console.error)
      .finally(() => setIsLoading(false));
  }, []);

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await savePlatformSettings({
        pdf_report_title: settings.pdf_report_title,
        pdf_footer_text: settings.pdf_footer_text,
        pdf_include_logo: settings.pdf_include_logo,
        pdf_show_page_numbers: settings.pdf_show_page_numbers,
        pdf_date_format: settings.pdf_date_format,
        pdf_currency: settings.pdf_currency,
        pdf_paper_size: settings.pdf_paper_size,
        pdf_orientation: settings.pdf_orientation,
      });
      setSaved(true);
      toast.success('Report settings saved');
      setTimeout(() => setSaved(false), 2500);
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : 'Failed to save');
    } finally {
      setIsSaving(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64"><Loader2 size={24} className="animate-spin text-accent" /></div>
    );
  }

  return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-700 text-foreground">PDF & Report Settings</h1>
            <p className="text-sm text-muted-foreground mt-0.5">Configure report templates and export options</p>
          </div>
          <button onClick={handleSave} disabled={isSaving} className={`btn-primary ${saved ? 'bg-positive' : ''}`}>
            {isSaving ? <Loader2 size={15} className="animate-spin" /> : saved ? <Check size={15} /> : <FileText size={15} />}
            {saved ? 'Saved' : 'Save Settings'}
          </button>
        </div>

        <div className="card-elevated p-5 space-y-4">
          <h2 className="text-base font-600 text-foreground">Report Header & Footer</h2>
          <div>
            <label className="block text-sm font-600 text-foreground mb-1.5">Report Title</label>
            <input type="text" className="input-base" value={settings.pdf_report_title} onChange={(e) => setSettings((s) => ({ ...s, pdf_report_title: e.target.value }))} />
          </div>
          <div>
            <label className="block text-sm font-600 text-foreground mb-1.5">Footer Text</label>
            <input type="text" className="input-base" value={settings.pdf_footer_text} onChange={(e) => setSettings((s) => ({ ...s, pdf_footer_text: e.target.value }))} />
          </div>
          {[
            { key: 'pdf_include_logo' as const, label: 'Show logo in reports', desc: 'Include app logo in PDF header' },
            { key: 'pdf_show_page_numbers' as const, label: 'Show page numbers', desc: 'Add page numbers to multi-page reports' },
          ].map((item) => (
            <div key={item.key} className="flex items-center justify-between p-3 rounded-xl border border-border">
              <div>
                <p className="text-sm font-600 text-foreground">{item.label}</p>
                <p className="text-xs text-muted-foreground">{item.desc}</p>
              </div>
              <button
                onClick={() => setSettings((s) => ({ ...s, [item.key]: !s[item.key] }))}
                className={`relative w-10 h-5 rounded-full transition-colors cursor-pointer ${settings[item.key] ? 'bg-accent' : 'bg-muted'}`}
                aria-label={`Toggle ${item.label}`}
              >
                <span className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-all duration-200 ${settings[item.key] ? 'start-5' : 'start-0.5'}`} />
              </button>
            </div>
          ))}
        </div>

        <div className="card-elevated p-5 space-y-4">
          <h2 className="text-base font-600 text-foreground">Format Settings</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-600 text-foreground mb-1.5">Date Format</label>
              <select className="input-base" value={settings.pdf_date_format} onChange={(e) => setSettings((s) => ({ ...s, pdf_date_format: e.target.value }))}>
                <option value="DD/MM/YYYY">DD/MM/YYYY</option>
                <option value="MM/DD/YYYY">MM/DD/YYYY</option>
                <option value="YYYY-MM-DD">YYYY-MM-DD</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-600 text-foreground mb-1.5">Paper Size</label>
              <select className="input-base" value={settings.pdf_paper_size} onChange={(e) => setSettings((s) => ({ ...s, pdf_paper_size: e.target.value }))}>
                <option value="A4">A4</option>
                <option value="Letter">Letter</option>
                <option value="Legal">Legal</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-600 text-foreground mb-1.5">Orientation</label>
              <select className="input-base" value={settings.pdf_orientation} onChange={(e) => setSettings((s) => ({ ...s, pdf_orientation: e.target.value }))}>
                <option value="portrait">Portrait</option>
                <option value="landscape">Landscape</option>
              </select>
            </div>
          </div>
        </div>

        <div className="card-elevated p-4 border-l-4 border-accent">
          <p className="text-sm font-600 text-foreground mb-1">PDF Generation</p>
          <p className="text-xs text-muted-foreground">
            PDF generation uses the browser&apos;s print dialog (window.print). For server-side PDF generation with custom templates, a Supabase Edge Function with a PDF library (e.g., Puppeteer) is required in Phase 2.
          </p>
        </div>
      </div>
  );
}
