-- ============================================================
-- Smart Pocket Phase 1 — Corrective & Additive Migration
-- Migration: 20260615160000_phase1_corrective_safe.sql
-- ⚠️  SAFE MIGRATION — NO DROP TABLE, NO DROP TYPE CASCADE
-- All operations use CREATE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS
-- Safe to run multiple times (fully idempotent).
-- ============================================================

-- ============================================================
-- 1. ADD MISSING COLUMNS TO platform_settings (safe)
-- ============================================================
ALTER TABLE public.platform_settings
  ADD COLUMN IF NOT EXISTS app_name TEXT DEFAULT 'Smart Pocket',
  ADD COLUMN IF NOT EXISTS tagline TEXT DEFAULT 'Personal Finance, Simplified',
  ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#0f3460',
  ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '#00b4d8',
  ADD COLUMN IF NOT EXISTS logo_url TEXT DEFAULT '/assets/images/app_logo.png',
  ADD COLUMN IF NOT EXISTS favicon_url TEXT DEFAULT '/favicon.ico',
  ADD COLUMN IF NOT EXISTS font_family TEXT DEFAULT 'Plus Jakarta Sans',
  ADD COLUMN IF NOT EXISTS site_title TEXT DEFAULT 'Smart Pocket — Personal Finance, Simplified',
  ADD COLUMN IF NOT EXISTS site_description TEXT DEFAULT 'Smart Pocket helps you track income, expenses, budgets, and financial accounts.',
  ADD COLUMN IF NOT EXISTS og_image TEXT DEFAULT '/assets/images/app_logo.png',
  ADD COLUMN IF NOT EXISTS twitter_handle TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS google_analytics_id TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS canonical_url TEXT DEFAULT 'https://smartpocke9976.builtwithrocket.new',
  ADD COLUMN IF NOT EXISTS robots_index BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS sitemap_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS email_provider TEXT DEFAULT 'supabase',
  ADD COLUMN IF NOT EXISTS smtp_host TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS smtp_port TEXT DEFAULT '587',
  ADD COLUMN IF NOT EXISTS smtp_user TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS from_email TEXT DEFAULT 'noreply@smartpocket.app',
  ADD COLUMN IF NOT EXISTS from_name TEXT DEFAULT 'Smart Pocket',
  ADD COLUMN IF NOT EXISTS google_oauth_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS apple_oauth_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS magic_link_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS password_min_length INTEGER DEFAULT 8,
  ADD COLUMN IF NOT EXISTS require_email_verification BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS pdf_paper_size TEXT DEFAULT 'A4',
  ADD COLUMN IF NOT EXISTS pdf_orientation TEXT DEFAULT 'portrait',
  ADD COLUMN IF NOT EXISTS pdf_include_logo BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS pdf_footer_text TEXT DEFAULT 'Generated by Smart Pocket',
  ADD COLUMN IF NOT EXISTS header_menu JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS footer_sections JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS contact_email TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_phone TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS payment_stripe_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_paypal_enabled BOOLEAN DEFAULT false;

-- ============================================================
-- 2. UPDATED_AT TRIGGERS FOR FINANCE TABLES (safe)
-- ============================================================
DROP TRIGGER IF EXISTS set_updated_at_financial_accounts ON public.financial_accounts;
CREATE TRIGGER set_updated_at_financial_accounts
  BEFORE UPDATE ON public.financial_accounts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_categories ON public.categories;
CREATE TRIGGER set_updated_at_categories
  BEFORE UPDATE ON public.categories
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_transactions ON public.transactions;
CREATE TRIGGER set_updated_at_transactions
  BEFORE UPDATE ON public.transactions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_budgets ON public.budgets;
CREATE TRIGGER set_updated_at_budgets
  BEFORE UPDATE ON public.budgets
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_recurring_transactions ON public.recurring_transactions;
CREATE TRIGGER set_updated_at_recurring_transactions
  BEFORE UPDATE ON public.recurring_transactions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_transfers ON public.transfers;
CREATE TRIGGER set_updated_at_transfers
  BEFORE UPDATE ON public.transfers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 3. DEDUPLICATE SYSTEM CATEGORIES, THEN ADD UNIQUE CONSTRAINT
-- Removes duplicate system category rows (keeping the oldest
-- by ctid) before adding the unique constraint, so this block
-- is safe even when the table already contains duplicates.
-- ============================================================
DO $$
BEGIN
  -- Step 1: Remove duplicate system categories, keeping the
  -- row with the smallest ctid (physical insertion order).
  DELETE FROM public.categories a
  USING public.categories b
  WHERE a.is_system = true
    AND b.is_system = true
    AND a.name = b.name
    AND a.category_type = b.category_type
    AND a.ctid > b.ctid;

  -- Step 2: Add unique constraint only if it does not exist yet.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_system_categories_name_type'
      AND conrelid = 'public.categories'::regclass
  ) THEN
    ALTER TABLE public.categories
      ADD CONSTRAINT uq_system_categories_name_type
      UNIQUE (name, category_type);
  END IF;
END;
$$;

-- ============================================================
-- 4. STORAGE BUCKET POLICIES (RLS for storage.objects)
-- ============================================================

-- receipts bucket: private, authenticated users access own files
DROP POLICY IF EXISTS "receipts_user_insert" ON storage.objects;
CREATE POLICY "receipts_user_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'receipts' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "receipts_user_select" ON storage.objects;
CREATE POLICY "receipts_user_select" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'receipts' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "receipts_user_delete" ON storage.objects;
CREATE POLICY "receipts_user_delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'receipts' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- avatars bucket: public read, authenticated write own
DROP POLICY IF EXISTS "avatars_public_read" ON storage.objects;
CREATE POLICY "avatars_public_read" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "avatars_user_insert" ON storage.objects;
CREATE POLICY "avatars_user_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'avatars' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "avatars_user_update" ON storage.objects;
CREATE POLICY "avatars_user_update" ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'avatars' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "avatars_user_delete" ON storage.objects;
CREATE POLICY "avatars_user_delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'avatars' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- exports bucket: private, authenticated users access own files
DROP POLICY IF EXISTS "exports_user_insert" ON storage.objects;
CREATE POLICY "exports_user_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'exports' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "exports_user_select" ON storage.objects;
CREATE POLICY "exports_user_select" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'exports' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "exports_user_delete" ON storage.objects;
CREATE POLICY "exports_user_delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'exports' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- ============================================================
-- 5. ADMIN RLS POLICY FOR platform_settings (safe update)
-- ============================================================
DROP POLICY IF EXISTS "admin_manage_platform_settings" ON public.platform_settings;
CREATE POLICY "admin_manage_platform_settings" ON public.platform_settings
  FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "authenticated_read_platform_settings" ON public.platform_settings;
CREATE POLICY "authenticated_read_platform_settings" ON public.platform_settings
  FOR SELECT TO authenticated
  USING (true);

-- ============================================================
-- 6. SYSTEM CATEGORIES SEED — idempotent via ON CONFLICT
-- Relies on uq_system_categories_name_type constraint above.
-- Safe to run multiple times — will never insert duplicates.
-- ============================================================
INSERT INTO public.categories (id, user_id, name, category_type, color, icon, is_system, sort_order)
VALUES
  (gen_random_uuid(), NULL, 'Salary',         'income',   '#059669', 'TrendingUp',     true, 1),
  (gen_random_uuid(), NULL, 'Freelance',       'income',   '#10b981', 'Briefcase',      true, 2),
  (gen_random_uuid(), NULL, 'Investment',      'income',   '#0ea5e9', 'BarChart2',      true, 3),
  (gen_random_uuid(), NULL, 'Other Income',    'income',   '#6366f1', 'Plus',           true, 4),
  (gen_random_uuid(), NULL, 'Housing',         'expense',  '#7c3aed', 'Home',           true, 10),
  (gen_random_uuid(), NULL, 'Food & Dining',   'expense',  '#f97316', 'Utensils',       true, 11),
  (gen_random_uuid(), NULL, 'Transport',       'expense',  '#2563eb', 'Car',            true, 12),
  (gen_random_uuid(), NULL, 'Utilities',       'expense',  '#8b5cf6', 'Zap',            true, 13),
  (gen_random_uuid(), NULL, 'Shopping',        'expense',  '#d97706', 'ShoppingBag',    true, 14),
  (gen_random_uuid(), NULL, 'Healthcare',      'expense',  '#ec4899', 'Heart',          true, 15),
  (gen_random_uuid(), NULL, 'Entertainment',   'expense',  '#dc2626', 'Gamepad2',       true, 16),
  (gen_random_uuid(), NULL, 'Travel',          'expense',  '#0ea5a0', 'Plane',          true, 17),
  (gen_random_uuid(), NULL, 'Education',       'expense',  '#0284c7', 'BookOpen',       true, 18),
  (gen_random_uuid(), NULL, 'Personal Care',   'expense',  '#db2777', 'Smile',          true, 19),
  (gen_random_uuid(), NULL, 'Subscriptions',   'expense',  '#7c3aed', 'Repeat',         true, 20),
  (gen_random_uuid(), NULL, 'Other Expense',   'expense',  '#6b7280', 'Tag',            true, 21),
  (gen_random_uuid(), NULL, 'Transfer',        'transfer', '#0ea5e9', 'ArrowLeftRight', true, 30)
ON CONFLICT (name, category_type) DO NOTHING;
