-- ============================================================
-- Smart Pocket Phase 1 — Add missing platform_settings columns
-- Migration: 20260615180000_platform_settings_extra_columns.sql
-- Safe, idempotent — uses ADD COLUMN IF NOT EXISTS
-- ============================================================

ALTER TABLE public.platform_settings
  ADD COLUMN IF NOT EXISTS singleton_lock BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS header_menu JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS footer_sections JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS contact_email TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_phone TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS payment_stripe_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_paypal_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS google_oauth_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS apple_oauth_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS magic_link_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS require_email_verification BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS password_min_length INTEGER DEFAULT 8,
  ADD COLUMN IF NOT EXISTS pdf_report_title TEXT DEFAULT 'Smart Pocket Financial Report',
  ADD COLUMN IF NOT EXISTS pdf_footer_text TEXT DEFAULT 'Generated by Smart Pocket — Personal Finance, Simplified',
  ADD COLUMN IF NOT EXISTS pdf_include_logo BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS pdf_show_page_numbers BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS pdf_date_format TEXT DEFAULT 'DD/MM/YYYY',
  ADD COLUMN IF NOT EXISTS pdf_currency TEXT DEFAULT 'AED',
  ADD COLUMN IF NOT EXISTS pdf_paper_size TEXT DEFAULT 'A4',
  ADD COLUMN IF NOT EXISTS pdf_orientation TEXT DEFAULT 'portrait',
  ADD COLUMN IF NOT EXISTS hero_title TEXT DEFAULT 'Take control of your financial life',
  ADD COLUMN IF NOT EXISTS hero_subtitle TEXT DEFAULT 'Smart Pocket helps you track income, expenses, budgets, and accounts with professional reporting — all in one beautiful app.',
  ADD COLUMN IF NOT EXISTS hero_cta_primary TEXT DEFAULT 'Get Started Free',
  ADD COLUMN IF NOT EXISTS hero_cta_secondary TEXT DEFAULT 'See Features';

-- Ensure singleton row exists
INSERT INTO public.platform_settings (singleton_lock)
SELECT true
WHERE NOT EXISTS (SELECT 1 FROM public.platform_settings);
